version: '3.1'

services:
  s_api_gateway:
    container_name: c_api_gateway
    image: haluk/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - 1000:1000
    networks:
      - micro_net
      - int_net

  s_contact_api:
    container_name: c_contact_api
    image: FahrettinSolak/contactapi
    build:
      context: .
      dockerfile: Services/ContactAPI/Contact.API
    ports:
      - 44390:44390
    networks:
      - int_net

  s_res_api:
    container_name: c_res_api
    image: FahrettinSolak/contactapi
    build:
      context: .
      dockerfile: Services/ResAPI/Reservation.API
    ports:
      - 44370:44370
    networks:
      - int_net

networks:
  int_net:
    driver: overlay
    internal: true
  micro_net:
    driver: bridge